### ISSUE TITLE
they put anything nearly for burning

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#597] opened 2017-01-15 21:03 UTC
they useing anything close now for refueling. they where putting sand in my stove and such.

**Comment by notfood** [comment] 2017-01-15 21:24
That's hilarious.

Clear the filter and set it again? Can you try it in a new save?

**Comment by sidfu** [comment] 2017-01-15 21:25
seems it kinda settles out after a while so far. after around 10min they stoped it. maybe some data was saved in save and took a while before it changed into the changes.

and yeah funny they put ssand in a stove lol. i did clear it at first and console rebuilt it and was same. have to see as i play more if it stays right.

**Comment by notfood** [comment] 2017-01-15 21:55
Possibly old save issue. Check with new save.

**Comment by notfood** [comment] 2017-01-17 02:21
Closing this. Can't reproduce.

**Closed by notfood** 2017-01-17 02:21 UTC
