### ISSUE TITLE
There is Marine Shirt item but no its recipe.

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1710] opened 2019-03-26 02:16 UTC
Is it intended?
![2019-03-26 (1)](https://user-images.githubusercontent.com/11158226/54966742-a27a1f80-4fb8-11e9-8205-0d3fbc174f36.png)

**Comment by vladimirlashko** [comment] 2019-03-30 07:21
I have the same issue. Moreover, a lot of apparel can't be crafted too. e.g. Spurred boots, Armor MK2...

**Comment by sidfu** [comment] 2019-03-30 08:40
not a bug. some items where moved to the quest system to get people to do stuff outside their base.

**Comment by masakitenchi** [comment] 2024-06-29 00:16
Closed as too old

**Closed by masakitenchi** 2024-06-29 00:16 UTC
