### ISSUE TITLE
(A14) Interaction point bug

### ISSUE THREAD

**Issue by Vulpes-Inculta** [skyarkhangel/Hardcore-SK#665] opened 2017-01-27 16:48 UTC
I can't place any seat (not even simplest stool) at any interaction point of any facilities. This is weird... Didn't happen in older mod versions of A14 when I last time played it. Hardcore-SK-4.2.1 release.

I know, A14 version is not supported anymore but A16 isn't playable yet and this bug is huge and game/immersion breaking for me. Maybe someone knows how to fix it? How to make at least backless stool placeable at interaction points... Thanks!

**Comment by sidfu** [comment] 2017-01-27 17:02
its not a bug. the stuff just didnt have it enabled. u just have to go to each and every chair and add it your self.

**Comment by Vulpes-Inculta** [comment] 2017-01-27 18:33
Hey thank you, but add what?

**Comment by sidfu** [comment] 2017-01-27 20:49
a16 already has that changed. btw close this also

**Closed** 2017-01-27 21:04 UTC
