### ISSUE TITLE
Flies and mosquitoes quickly consume all the starting survival food

### ISSUE THREAD

**Issue by l29ah** [skyarkhangel/Hardcore-SK#1929] opened 2019-11-01 02:24 UTC
As seen when starting in jungles. This doesn't seem plausible since the insects are tiny, and there aren't that many of them.

**Comment by sidfu** [comment] 2019-11-01 02:26
not a bug. just pickup all the food and carry it till u have a place for it

**Comment by masakitenchi** [comment] 2024-06-29 00:10
Closed as too old

**Closed by masakitenchi** 2024-06-29 00:10 UTC
