### ISSUE TITLE
some traders don't have money and anything to buy (mostly space trader)

### ISSUE THREAD

**Issue by crusender** [skyarkhangel/Hardcore-SK#37] opened 2016-02-26 18:42 UTC
time to time whit any kind of trader that happen

**Comment by skyarkhangel** [comment] 2016-02-27 22:33
You are right. I'am already trying to find the cause of the error. If  you have a clue, at what moment, may be specific merchant... etc.

**Comment by crusender** [comment] 2016-02-28 06:52
often it is mostly the pirate merchant , but there is too other kind and sometime i see it there is a spawn of 3 of them at sametime. now craft merchant dont buy/sell any kind leathers. salve trader dont have any kind of slave to sell.

**Comment by DanteValerian** [comment] 2016-02-28 17:59
I posted a possible solution to this problem on the Ludeon forum thread for the mod a few minutes ago.

**Comment by Masquerine** [comment] 2016-02-28 22:05
Working on it right now. I think I have it all working correctly. I'm just testing to make sure.

**Comment by crusender** [comment] 2016-02-29 00:37
just test it and look like fix about all the no money stuff and no slave but still not leather seller/buyer

**Comment by Masquerine** [comment] 2016-02-29 00:45
Oh, forgot to add that in haha. I'll do that now.

**Comment by Masquerine** [comment] 2016-02-29 13:56
Traders seem to be working fine now, so I'll close this.

**Closed by Masquerine** 2016-02-29 13:56 UTC
