### ISSUE TITLE
Animals immediately rot

### ISSUE THREAD

**Issue by Leslac** [skyarkhangel/Hardcore-SK#2849] opened 2021-03-14 19:03 UTC
I'm playing on the no-dlc most recent stable version of the H-SK and I'm seeing something really odd. Animals get killed by my hunters immediately rot.

 Their status is all set as having "serious" toxic buildup. The instrument of murder was a crossbow with metallic bolts. There's been no toxic fallout recently...

 Is there maybe a bug with the toxic buildup status?

**Comment by zakhad** [comment] 2021-03-14 19:07
Any creature with toxic buildup upon death has a chance of instantly rotting.

**Comment by Leslac** [comment] 2021-03-14 19:11
Yeah, that's the thing. When they're killed there's no toxic buildup. But when dead, their status is immediately set as serious toxic buildup. The same thing happens with animals killed by predators all over the map. So there are a lot of rotting animals lying around...

 I had a weird recent event stating something about all non-humans dying out on the planet, but saw no consequence of it (my colony had no non-humans in it). Maybe it has something to do with that?

**Comment by zakhad** [comment] 2021-03-14 19:18
I'm not entirely certain but the animal genocide event i think was changed to cause all non colony animals on the map it happens on to suddenly have a massive toxic buildup that kills them off, they used to just be arbitrarily just slain but now they die of toxic buildup but some do survive.

**Comment by Leslac** [comment] 2021-03-14 19:21
It's probably that then. Is it a bug that I can't see the toxic status in the animals? None of the animals on the map have toxic buildup or look like they're dying from it...

**Comment by zakhad** [comment] 2021-03-14 19:26
I think it's hidden if it's minor or less, it should be visible i believe if it's higher than that.

**Comment by Leslac** [comment] 2021-03-14 19:29
Well there seem to be something funky going on... On death animals immediately rot because of toxic buildup that's invisible. Maybe have a look at the event? Also it didn't come as a popup, but as an on-screen message (like "summer is here") and it stated clearly "all non-human species on the planet have died off". A really WTF event?

**Comment by zakhad** [comment] 2021-03-14 19:47
No it's working as intended, use the dev tools see if they actually have the toxic buildup, if they do then it's working as intended. A lot of diseases & toxic buildup simply wouldn't be noticeable until it progresses past a certain point, anyone can be a carrier for the flu irl but it wouldn't be noticeable until it's incubated for a while, like how if someone sneezes on you, you don't instantly become sick it takes a while. 

The whole corpse rot if it has toxic buildup is a vanilia thing, but the animal genocide is a HSK thing, it's just how the game play's it's not fair that is intended, it's a hardcore modpack after all, i'm sorry if you don'r like that, but i don't actually see a problem with how this is functioning.

**Comment by zakhad** [comment] 2021-03-14 19:50
Basically be on the mindset of, oh i killed that animal but i didn't realise it was diseased you technically don't know if any animal if viable for eating until you've killed it and checked it over, you need to be more immersed, if you're in a situation where you are reliant upon that 1 kill then you are doing something grossly wrong with how your playing, go travel to another tile with some hunters go hunt, butcher some corpses with butchering spots carry the meat back, sometimes that's how you have to do it to survive.

**Comment by Leslac** [comment] 2021-03-14 19:57
Oh it's a fine event. It's just the implementation that's weird. Not a pop-up and it doesn't do what it says.

 Instead of "all non-human species have died off" it should state something like "animals across the planets are dying off from a mysterious ailment." Because actual non-human species (blue aliens, mouse-people etc.) aren't affected by it.

 Like it is now, it's just a confusing event that you have like ten seconds to read and try to fathom what it means. And it hides the effect in animals, while I was looking at my colonists and to see if neighbouring tribes had vanished.

**Comment by zakhad** [comment] 2021-03-14 20:07
Yeah i'll give you that, a lot of stuff needs rewrites, lots of tech research information is wrong as well, the research is being overhauled but i couldn't say when that'll get released if or when it does, i'll most likely clean up a lot of misinformation for the English folks.

Going to close this issue as resolved if you want to discuss it further you can tag me in the discord server.

**Closed by zakhad** 2021-03-14 20:07 UTC
