### ISSUE TITLE
All events stopped. 

### ISSUE THREAD

**Issue by Rufert** [skyarkhangel/Hardcore-SK#409] opened 2016-10-15 10:57 UTC
Had one wanderer join and one escape pod in the first week. Been two years now and not a single event has occurred. With Cassandra classic on rough. 

Using the newest version as of this posting.

**Comment by FalyPr1nc3** [comment] 2016-10-15 23:07
I have the same issue. Cassandra, 3 difficulty, hardcore.
I tried about 10 times, no events after reinforcement at all.

**Comment by skyarkhangel** [comment] 2016-10-16 04:46
Ohh ok. Plz fix your savegame. its related to raid generator update.

Find in savegame:
			<incidentQueue>
			</incidentQueue>

if anything exist inside, delete.

**Comment by FalyPr1nc3** [comment] 2016-10-16 17:31
Looks like you have fixed it.
Thanks!

**Comment by Rufert** [comment] 2016-10-18 03:34
The savegame fix works, but eventually it happens again and once again needs fixing.
I'm not sure what exactly causes it since it always takes me a while to notice.

**Comment by Rufert** [comment] 2016-10-18 04:41
Hm, no. Fixing it stopped working. Having no events for a long time.
I've uploaded the save file. hopefully someone smarter than me will be able to make sense of it.
https://drive.google.com/file/d/0B5xbtBADXxBnWU1keEtVaG1nWDQ/view?usp=sharing

**Comment by skyarkhangel** [comment] 2016-10-18 11:26
I'am updated raidgenerator some days ago. there is a difference? errors?

**Comment by Rufert** [comment] 2016-10-18 11:34
How many days ago? My version is 3 days old.
I haven't gotten any errors at all, events just stop. Randy rough this time.

**Comment by zakhad** [comment] 2016-10-20 14:32
After experiencing this error myself I decided to come here to see whether or not anyone else was having this error and people have been. At the time the only difference I could ascertain was that I was also getting GetRoom() errors which was related to Hospitality. While looking at that error, I found this interesting bug discussion, which I believe to be related.

Hospitality mod thread.

Quoting Orion

"There was a bug in the previous version that caused visitors to not come, while you had prisoners from any hostile faction. This caused some people to not have visitors for several years. This is fixed now and visitors won't give a damn about prisoners. It would indeed make sense that they'd care about their own. But it's a rare scenario."

I can confirm when I have a prisoner I barely get raided at all other than insectoids / other custom factions you've made such as asari which haven't been tied in to Hospitality.

So that this might be whats causing the serve lack of events happening or might somehow conflicting with the new raid generator that you've been working on sky.

These issues have been fixed in his newer version but its for alpha 15, When he updated his mod from alpha 14 to alpha 15 he pulled the dependency on CCL so it no longer needs it and runs independently which might make backporting Hospitality  to alpha 14 easier, unless you plan on updating to alpha 15 anytime soon.

**Comment by Rufert** [comment] 2016-10-20 16:18
It isn't just raids and visitors Sackhad, it's everything, infection, environmental effects, blight ect.

**Comment by zakhad** [comment] 2016-10-21 01:16
It's just a hypothesis: What I have mentioned is plausible as to why events depending (all/some) could stop. The only difference is that I had a newer version with some changes to the IncidentDefs when compared to yours, specifically I was using commit 9511a64db127dc28e07a43fe2d146a11d50afe84 so the end results might be slightly different. (some events vs none) I'm still having, what I'm to believe to be a large deficiency in events. But as my hypothesis goes, by solving the raid and visitor bug with hospitality, we might find out that it's actually only a "everything infections environmental effects" problem,  or I could be wrong but that's why it's a hypothesis. And please no synonyms towards my handle, I can't tell if your jesting as I don't know you.

Also I'm not sure by when you say " log only pops up when there are errors. So I'm assuming there are none since I haven't seen it open." did you know that you can toggle the console to open manually with dev mode enabled by pressing "tilde" - it could be different depending on your keyboard layout.

This is the error I'm getting constantly spamming
![error](https://cloud.githubusercontent.com/assets/5264667/19583329/a32f979c-9733-11e6-945d-2e7c7e9737fb.jpg)
Which would indicate a bad reference somewhere.

**Comment by skyarkhangel** [comment] 2016-12-01 07:54
So, soon start update to a15.

**Closed by skyarkhangel** 2016-12-01 07:54 UTC
