### ISSUE TITLE
Spawn errors

### ISSUE THREAD

**Issue by freijie** [skyarkhangel/Hardcore-SK#680] opened 2017-01-29 23:45 UTC
NovaAlliance has no usable PawnGroupMakers 

```
Faction Haunt of def NovaAlliance has no usable PawnGroupMakers for parms map=Map 0 (ID 0) (player home) (current), points=143, faction=Haunt, traderKind=, generateFightersOnly=False, generateMeleeOnly=False, raidStrategy=, forceOneIncap=False
Verse.Log:Error(String)
RimWorld.<GeneratePawns>c__IteratorC4:MoveNext()
System.Collections.Generic.List`1:AddEnumerable(IEnumerable`1)
System.Collections.Generic.List`1:.ctor(IEnumerable`1)
System.Linq.Enumerable:ToList(IEnumerable`1)
RimWorld.IncidentWorker_NeutralGroup:SpawnPawns(IncidentParms)
Hospitality.IncidentWorker_VisitorGroup:TryExecute(IncidentParms)
RimWorld.Storyteller:TryFire(FiringIncident)
RimWorld.Storyteller:StorytellerTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()
```
=====================================
Orassan has no usable PawnGroupMakers 

```
Faction Southern Onhendo Kin League of def Orassan has no usable PawnGroupMakers for parms map=Map 0 (ID 0) (player home) (current), points=51, faction=Southern Onhendo Kin League, traderKind=, generateFightersOnly=False, generateMeleeOnly=False, raidStrategy=, forceOneIncap=False
Verse.Log:Error(String)
RimWorld.<GeneratePawns>c__IteratorC4:MoveNext()
System.Collections.Generic.List`1:AddEnumerable(IEnumerable`1)
System.Collections.Generic.List`1:.ctor(IEnumerable`1)
System.Linq.Enumerable:ToList(IEnumerable`1)
RimWorld.IncidentWorker_NeutralGroup:SpawnPawns(IncidentParms)
Hospitality.IncidentWorker_VisitorGroup:TryExecute(IncidentParms)
RimWorld.Storyteller:TryFire(FiringIncident)
RimWorld.Storyteller:StorytellerTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()
```
=====================================
Failed Raid (no further messages in log)

```
Got no pawns spawning raid from parms (points=917.2529 raidStrategy=ImmediateAttackSappers )
Verse.Log:Error(String)
RimWorld.IncidentWorker_Raid:TryExecute(IncidentParms)
SK.Events.IncidentWorker_RaidEnemyFix:TryExecute(IncidentParms)
RimWorld.Storyteller:TryFire(FiringIncident)
RimWorld.Storyteller:StorytellerTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()
```
=====================================
Feral has no usable PawnGroupMakers 

```
Faction Coalition of Barbrei of def Feral has no usable PawnGroupMakers for parms map=Map 0 (ID 0) (player home) (current), points=1407.73, faction=Coalition of Barbrei, traderKind=, generateFightersOnly=False, generateMeleeOnly=False, raidStrategy=ImmediateAttackSappers, forceOneIncap=False
Verse.Log:Error(String)
RimWorld.<GeneratePawns>c__IteratorC4:MoveNext()
System.Collections.Generic.List`1:AddEnumerable(IEnumerable`1)
System.Collections.Generic.List`1:.ctor(IEnumerable`1)
System.Linq.Enumerable:ToList(IEnumerable`1)
RimWorld.IncidentWorker_Raid:TryExecute(IncidentParms)
SK.Events.IncidentWorker_RaidEnemyFix:TryExecute(IncidentParms)
RimWorld.Storyteller:TryFire(FiringIncident)
RimWorld.Storyteller:StorytellerTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()
```

=====================================
Antis Raid (successful spawn)

```
System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.IncidentWorker_Raid.TryExecute (RimWorld.IncidentParms parms) [0x00000] in <filename unknown>:0 
  at SK.Events.IncidentWorker_RaidEnemyFix.TryExecute (RimWorld.IncidentParms parms) [0x00000] in <filename unknown>:0 
  at RimWorld.Storyteller.TryFire (RimWorld.FiringIncident fi) [0x00000] in <filename unknown>:0 
  at RimWorld.Storyteller.StorytellerTick () [0x00000] in <filename unknown>:0 
  at Verse.TickManager.DoSingleTick () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

```

=====================================
Spawn abomination from unopened capsule. (no abomination, capsule dropped some food items after opening)

```
Tried to get valid region out of bounds at (-1000, -1000, -1000)
Verse.Log:Error(String)
Verse.RegionGrid:GetValidRegionAt(IntVec3)
Verse.GridsUtility:GetRegion(IntVec3, Map)
Verse.CellFinder:TryFindRandomReachableCellNear(IntVec3, Map, Single, TraverseParms, Predicate`1, Predicate`1, IntVec3&, Int32)
Verse.CellFinder:RandomClosewalkCellNear(IntVec3, Map, Int32)
SK.Events.Ticker_MTcounter:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

Got ThingsListAt out of bounds: (-1000, -1000, -1000)
Verse.Log:Error(String)
Verse.Log:ErrorOnce(String, Int32)
Verse.ThingGrid:ThingsListAt(IntVec3)
Verse.GridsUtility:GetThingList(IntVec3, Map)
RimWorld.FilthMaker:MakeFilth(IntVec3, Map, ThingDef, IEnumerable`1, Boolean)
RimWorld.FilthMaker:MakeFilth(IntVec3, Map, ThingDef, Int32)
SK.Events.Ticker_MTcounter:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

Tried to spawn Abomination259216 out of bounds at (-1000, -1000, -1000).
Verse.Log:Error(String)
AlienRace.GenSpawnAlien:SpawnModded(Thing, IntVec3, Map, Rot4)
Verse.GenSpawn:Spawn(Thing, IntVec3, Map)
SK.Events.Ticker_MTcounter:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

```

**Comment by Dunkhan** [comment] 2017-02-01 21:10
Am I right in assuming this would result in no raids ever occurring? I am not getting any raids in the current version at all but I don't want to report a duplicate of this issue if it is the same problem.

**Comment by freijie** [comment] 2017-02-02 12:18
Most of the time this result in raid party not being formed, yes.

**Closed** 2017-06-22 00:19 UTC
